config/routes.rb
Rails.application.routes.draw do
  resources :orders

  devise_for :users
  resources :listings do 
		resources :orders
	end

  get 'pages/about'

  get 'pages/contact'
	
	get 'seller' => "listings#seller"
	get 'sales' => "orders#sales"
	get 'purchases' => "orders#purchases"
  
  root 'listings#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	validates :name, :descrption, :price, presence: true
	validates :price, numericality: { greater_than: 0}
	
	validates_presence_of :image
	
	belongs_to :user
	has_many :orders
end

app/models/order.rb
class Order < ActiveRecord::Base 
	validates :address, :city, :state, presence: true 
	belongs_to :listing 
	belongs_to :buyer, class_name: "User" 
	belongs_to :seller, class_name: "User" 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	validates :name, presence: true
	has_many :listings, dependent: :destroy
	has_many :sales, class_name: "Order", foreign_key: "seller_id" 
	has_many :purchases, class_name: "Order", foreign_key: "buyer_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.

	protect_from_forgery with: :exception

	before_filter :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) << :name
		devise_parameter_sanitizer.for(:account_update) << :name
	end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
	before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]

	def seller
		@listings = Listing.where(user: current_user).order("created_at DESC")
	end
  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all.order("created_at DESC")
  end
	
	

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
		@listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
			params.require(:listing).permit(:name, :descrption, :price, :image)
    end
	
	def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit]
	before_action :authenticate_user!

  # GET /orders
  # GET /orders.json
	def sales
		@orders = Order.all.where(seller: current_user).order("created_at DESC")
	end
	
	def purchases
		@orders = Order.all.where(buyer: current_user).order("created_at DESC")
	end
	
	def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
def new 
	@order = Order.new 
	@listing = Listing.find(params[:listing_id]) 
end 


  # GET /orders/1/edit

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params) 
		@listing = Listing.find(params[:listing_id]) 
		@seller = @listing.user 

		@order.listing_id = @listing.id 
		@order.buyer_id = current_user.id 
		@order.seller_id = @seller.id 

		respond_to do |format| 
			if @order.save 
				format.html { redirect_to root_url, notice: 'Order was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :city, :state)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
	def devise_error_messages!
		return '' if resource.errors.empty?

		messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
		sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)

		html = <<-HTML 
		<div class="alert alert-danger alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>

			<h4>#{sentence}</h4>
			#{messages}
		</div>
		HTML

		html.html_safe
	end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<p>copyright 2015</p>

app/views/layouts/_navbar.html.erb
<!-- <a href="/pages/about">About</a>
<a href="/pages/contact">Contact</a> -->
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Fletsy</a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
				<li><%= link_to "wassup", pages_about_path %></li>
				<li><%= link_to "HMU", pages_contact_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Seller Listings<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Sales History", sales_path %></li>
            <li><%= link_to "Purchase History", purchases_path %></li>
            <li><%= link_to "Manage Listings", seller_path %></li>
          </ul>
        </li>
				<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
						<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>

				<% else %>
					<li><%= link_to "Sign Up", new_user_registration_path %></li>
					<li><%= link_to "Sign In", new_user_session_path %></li>
				<% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Etsydemo</title>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/bootstrap/3.3.0/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/bootstrap/3.3.0/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navbar' %>
<div class="container">
	<div class="container"> <% flash.each do |name, msg| %> 
		<% if msg.is_a?(String) %> 
		<div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable"> 
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> 
		<%= content_tag :div, msg, :id => "flash_#{name}" %> 
		</div> 
		<% end %> 
		<% end %>
	<%= yield %>
	<%= render 'layouts/footer' %>
</div>
  <!-- Latest compiled and minified JavaScript -->
<script src="https://cdn.jsdelivr.net/bootstrap/3.3.0/js/bootstrap.min.js"></script>
</body>

</html>

app/views/listings/_form.html.erb
<%= form_for(@listing, :html => { :multipart => true }) do |f| %> 
	<% if @listing.errors.any? %> 
		<div id="error_explanation" class="alert alert-warning alert-dismissable"> 
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> 
			<h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4> 

			<ul> 
			<% @listing.errors.full_messages.each do |msg| %> 
				<li><%= msg %></li> 
			<% end %> 
			</ul> 
		</div> 
	<% end %>

  <div class="form-group">
    <%= f.label :name %><br>
		<%= f.text_field :name, class:"form-control", placeholder:"item name on fleek" %>
  </div>
  <div class="form-group">
    <%= f.label :descrption %><br>
		<%= f.text_area :descrption, class:"form-control", placeholder:"description on fleek" %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class:"form-control", placeholder:"pricing on fleek" %>
  </div>
  <div class="form-group">
		<%= f.label :image %><br>
		<%= f.file_field :image, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing, class:"btn btn-link" %> |
<%= link_to 'Back', listings_path, class:"btn btn-link" %>

app/views/listings/index.html.erb
<div class="jumbotron"> 
	<h1>#FreeMigos<br>AKA Quavo and Takeoff</h1> 
	<h2>As well as Bobby Schmurda, for that matter</h2>
</div>

<div class="center"> 
	<div class="row"> 
		<% @listings.each do |listing| %> 
		<div class="col-md-3">
			<div class="thumbnail"> 
				<%= link_to image_tag(listing.image.url), listing %> 
				<div class="caption"> 
					<h3><%= listing.name %></h3> 
					<p><%= number_to_currency(listing.price) %></p> 
					<p><%= "Sold by #{listing.user.name}" %></p> 
				</div> 
			</div> 
		</div> 
		<% end %> 
	</div> 
</div> 
<br> 
<% if user_signed_in? %> 
	<%= link_to 'New Listing', new_listing_path, class: "btn btn-link", data: { no_turbolink: true } %> 
<% end %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/seller.html.erb
<div class="center">
	<% if user_signed_in? %> 
		<%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %> 
	<% end %>
</div>
<div class="table-responsive">
  <table class="table table-striped table-bordered"> 
		<tr> 
			<th class="center">Image</th> 
			<th class="center">Name</th> 
			<th class="center">Description</th> 
			<th class="center">Price</th> 
			<th class="center">Action</th>
		</tr> 
		<% @listings.each do |listing| %> 
		<tr> 
			<td><%= image_tag listing.image_url(:thumb) %></td> 
			<td><%= listing.name %></td> 
			<td><%= listing.descrption %></td> 
			<td><%= number_to_currency(listing.price) %></td> 
			<td> 
				<div class="btn-group"> 
					<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"> Action 
						<span class="caret"></span> 
					</button> 
					<ul class="dropdown-menu" role="menu"> 
						<li><%= link_to "View", listing, class: "btn btn-link" %></li> 
						<li><%= link_to "Edit", edit_listing_path(listing), class: "btn btn-link" %></li> 
						<li><%= link_to "Destroy", listing, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link" %></li> 
					</ul> 
				</div> 
			</td>
		</tr> 
		<% end %> 
	</table> 
	<br> 
</div>

app/views/listings/show.html.erb
<div class="row">
	<div class="col-md-6">
		<div class="thumbnail">
		<%= image_tag @listing.image_url(:medium) %></div>
	</div>
  <div class="col-md-6">
		<h3>
			<%= @listing.name %>
		</h3>
		<h5>
			<%= number_to_currency(@listing.price) %>
		</h5>
		<h4>
			<%= @listing.descrption %>
		</h4>
		<br> 
		<div class="center"> 
			<%= link_to "Buy It Now", new_listing_order_path(@listing), class: "btn btn-primary" %> 
		</div> 
	</div>
</div>


<% if current_user == @listing.user %>
  <%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> |
<% end %>
<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/orders/_form.html.erb
<%= form_for([@listing, @order]) do |f| %> 
	<% if @order.errors.any? %> 
		<div id="error_explanation" class="alert alert-danger alert-dismissable"> 
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> 
			<h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group"> 
		<%= f.label :address %> 
		<%= f.text_field :address, class: "form-control" %> 
	</div> 
	<div class="form-group"> 
		<%= f.label :city %> 
		<%= f.text_field :city, class: "form-control" %> 
	</div> 
	<div class="form-group"> 
		<%= f.label :state %> 
		<%= f.text_field :state, class: "form-control" %> 
	</div> 
	<div class="form-group"> 
		<%= f.submit "Complete Order", class: "btn btn-success" %> 
	</div> 
<% end %>

app/views/orders/new.html.erb
<h1>New order</h1> 

<%= render 'form' %> 

<%= link_to 'Back', listing_path(@listing) %>

app/views/orders/purchases.html.erb
<div class="center">
	<h2>Your Purchase History</h2>
</div>

<div class="center">
	<% if user_signed_in? %> 
		<%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %> 
	<% end %>
</div>
<div class="table-responsive">
  <table class="table table-striped table-bordered"> 
		<tr> 
			<th class="center">Image</th> 
			<th class="center">Item</th> 
			<th class="center">Price</th> 
			<th class="center">Seller</th>
			<th class="center">Date Purchased</th>
		</tr> 
		<% @orders.each do |order| %> 
		<tr> 
			<td class="center"><%= image_tag order.listing.image_url(:thumb) %></td> 
			<td class="center"><%= order.listing.name %></td>  
			<td class="center"><%= number_to_currency(order.listing.price) %></td> 
			<td class="center"><%= order.seller.name %></td>
			<td class="center"><%= order.created_at.strftime("%B $-d, %Y") %></td>
		</tr> 
		<% end %> 
	</table> 
	<br> 
</div>

app/views/orders/sales.html.erb
<div class="center">
	<h2>Your Sales History</h2>
</div>

<div class="center">
	<% if user_signed_in? %> 
		<%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %> 
	<% end %>
</div>
<div class="table-responsive">
  <table class="table table-striped table-bordered"> 
		<tr> 
			<th class="center">Image</th> 
			<th class="center">Item</th> 
			<th class="center">Price</th> 
			<th class="center">Customer</th>
			<th class="center">Date Sold</th>
		</tr> 
		<% @orders.each do |order| %> 
		<tr> 
			<td class="center"><%= image_tag order.listing.image_url(:thumb) %></td> 
			<td class="center"><%= order.listing.name %></td>  
			<td class="center"><%= number_to_currency(order.listing.price) %></td> 
			<td class="center"><%= order.buyer.name %></td>
			<td class="center"><%= order.created_at.strftime("Done at %B $-d, %Y") %></td>
		</tr> 
		<% end %> 
	</table> 
	<br> 
</div>

app/views/pages/about.html.erb
<h1>Fletsy: Etsy for <em>hoodrats</em></h1>
<h2>Remy Boyz, yeaahhhh<br>
	1738</h2><br>

<h4>I'm like "hey, what's up, hello"<br>
Seen yo pretty face soon as you came in that door<br>
I just wanna chill, got a sack for us to roll<br>
Married to the money, introduced her to my stove<br>
	<a href="http://supersonic-winterfell-55-158841.use1.nitrousbox.com/listings/new" target="_blank">Posted it to Fletsy</a>, now she remixin' for low<br>
She my trap queen, let her hit the bando<br>
We be countin' up, watch how far them bands go<br>
We just made a listing, talkin' matchin' Lambos<br>
Got 50, 60 grand, 500 grams though<br>
Man, I swear I love her how she work the trap code<br>
Hit the iLab, we be letting bands go<br>
Everybody hating, we just call them fans though<br>
In love with the money, I ain't never letting go</h4><br>
<br>
<h3>[Hook]<br>
And I devise with my baby<br>
I just left the mall, I'm gettin' fly with my baby, yeaaahhh<br>
And I push live with my baby<br>
I be in the kitchen cookin' pies with my baby, yeaaahhh<br>
And I devise with my baby<br>
I just left the mall, I'm gettin' fly with my baby, yeaaahhh<br>
And I push live with my baby<br>
	I be in the kitchen cookin' pies with my baby</h3><br>
<br>
<h4>[Verse]<br>
I hit the lab with my trap queen cause all we know is bands<br>
I just might snatch up a 'Rari and buy my boo a Lamb'<br>
I might just snatch her a necklace, drop a couple on a ring<br>
She ain't wantin' for nothin' because I got her everything<br>
It's big Zoo Wap from the bando, without dinero can't go<br>
Remy Boyz got the stamp, though<br>
Count up hella, them bands though<br>
How far can your bands go?<br>
Fetty Wap I'm living fifty thousand K how I stand though<br>
	If you checkin' for my pockets I'm like<br></h4>
<br>
<h3>[Hook + Bridge]<br>
<br>
[Outro]<br>
	I be rake migratin, you know <a href="http://getbootstrap.com/" target="_blank"><strong>Bootstrap</strong></a> what I roll<br>
Remy Boyz, Fetty code the cleanest that's fasho<br>
I'll run in ya house, then I'll parse yo code<br>
	Cause Remy Boyz or nothin', Re-Re-Remy Boyz or nothin'</h3>
<br>
<h2>Yeah, you hear my girl<br>
	Lookin like a zillion bucks on <strong><a href="https://github.com/shelbsimone/fletsy" target="_blank">Github</a></strong><br>
Got whatever I'm up for it<br>
Put your money where your mouth is<br>
Repo on the wood make the game go good<br>
Repo outta site cause fights<br>
Put up or shut up, huh<br>
Knit the grit<br>
SSW Productions</h2>
	<br><br><br><br><br><br>
	
	<p><small><a href="https://www.youtube.com/watch?v=i_kF4zLNKio" target="_blank">squaaaaaaaaad</a></small></p>

app/views/pages/contact.html.erb
<h1>Email us at trapqueenzllc@fletsy.com</h1>